services:


  # cpu_generator:
  #   image: curlimages/curl:latest
  #   command: >
  #     sh -c "while true; do
  #              VALUE=$$((10 + RANDOM % 85));
  #              echo \"cpu_usage $$VALUE\" |
  #              curl -s --data-binary @- http://pushgateway:9091/metrics/job/demo/instance/demo-1;
  #              sleep 5;
  #            done"
  #   depends_on:
  #     - pushgateway


  java_cpu_generator:
    build: ./java-metric
    depends_on:
      - pushgateway
    environment:
      PGW_URL: pushgateway:9091
      JOB_NAME: java-demo
      INSTANCE: java-1
    restart: unless-stopped


  smtp:
    image: ixdotai/smtp:v0.7.6
    container_name: smtp
    ports:
      - 127.0.0.1:25:25
    env_file:
      - ./environments/smtp.env
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: my_data_db
      POSTGRES_USER: my_data_user
      POSTGRES_PASSWORD: my_data_pwd
    ports:
      - "5488:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

      
  loki:
    image: grafana/loki:3.4.3
    container_name: loki
    command:
      [
        "--validation.discover-service-name=[]",
        "--validation.discover-log-levels=false",
        "-config.file=/etc/loki/loki.yaml",
      ]
    volumes:
      - ./loki:/etc/loki/
    ports:
      - "3100:3100"

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager/
    ports:
      - 9093:9093
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.2.0}
    #image: grafana/grafana-oss:main
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp:25
      - GF_SMTP_SKIP_VERIFY=true
      - GF_FEATURE_TOGGLES_ENABLE=alertingCentralAlertHistory,sqlExpressions,alertingMigrationUI,grafanaManagedRecordingRules
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/alerting:/etc/grafana/provisioning/alerting
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
volumes:
  postgres:
    driver: local



